# Generated by Django 6.0.1 on 2026-01-30 23:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('button_click', 'Button Click'), ('form_start', 'Form Start'), ('form_complete', 'Form Complete'), ('template_view', 'Template View'), ('pricing_view', 'Pricing View')], max_length=50)),
                ('page_url', models.URLField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='analytics_e_event_t_7fd62a_idx'), models.Index(fields=['created_at'], name='analytics_e_created_3bce1d_idx'), models.Index(fields=['session_id'], name='analytics_e_session_b3cbf5_idx')],
            },
        ),
    ]
