/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Project Tokens
        "on-primary-fixed": "#131b2e",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#7c839b",
        "tertiary-container": "#271901",
        "inverse-on-surface": "#eff1f3",
        "surface-variant": "#e0e3e5",
        "on-tertiary-container": "#98805d",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        "on-secondary": "#ffffff",
        "tertiary": "#000000",
        "tertiary-fixed-dim": "#dec29a",
        "surface-tint": "#565e74",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "surface-container": "#eceef0",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "on-secondary-container": "#fefcff",
        "secondary-container": "#316bf3",
        "outline": "#76777d",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "on-surface-variant": "#45464d",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#fcdeb5",
        "surface-bright": "#f7f9fb",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#271901",
        "on-tertiary-fixed-variant": "#574425",
        "inverse-primary": "#bec6e0",
        "primary-container": "#131b2e",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#0051d5",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dae2fd",
        "primary": "#000000",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem"
      },
      fontFamily: {
        "headline": ["'Plus Jakarta Sans'", "sans-serif"],
        "body": ["'Inter'", "sans-serif"],
        "label": ["'Inter'", "sans-serif"],
        "sans": ["'Inter'", "sans-serif"]
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-red-500',
    'bg-blue-500',
    'bg-green-500',
    'text-red-500',
    'text-blue-500',
    'text-green-500',
    'text-blue-600',
    'text-green-600',
    'border-blue-600',
    'bg-blue-600',
    'bg-green-600',
    'bg-red-600',
  ],
}
