# Generated by Django 6.0.1 on 2026-01-30 23:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Plan name', max_length=255)),
                ('slug', models.SlugField(help_text='URL slug', max_length=255, unique=True)),
                ('price', models.CharField(help_text='Price display text', max_length=50)),
                ('price_label', models.CharField(blank=True, help_text='Price label (e.g., per month, one-time)', max_length=50, null=True)),
                ('description', models.TextField(help_text='Plan description')),
                ('features', models.JSONField(default=list, help_text='List of plan features')),
                ('contract_info', models.TextField(blank=True, help_text='Contract and safety information', null=True)),
                ('badge', models.CharField(blank=True, help_text='Badge text (e.g., Popular, Best Value)', max_length=50, null=True)),
                ('color', models.CharField(default='blue', help_text='Color theme for the plan', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('selection_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'db_table': 'pricing_plans',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='pricing_pla_is_acti_104ad1_idx'), models.Index(fields=['is_featured'], name='pricing_pla_is_feat_dd3107_idx'), models.Index(fields=['display_order'], name='pricing_pla_display_71f733_idx')],
            },
        ),
    ]
