# Generated by Django 6.0.1 on 2026-01-30 23:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Frontend session identifier', max_length=100)),
                ('event_type', models.CharField(choices=[('form_start', 'Form Started'), ('step_completed', 'Step Completed'), ('form_abandoned', 'Form Abandoned'), ('form_submitted', 'Form Submitted'), ('validation_error', 'Validation Error')], max_length=30)),
                ('step_number', models.PositiveIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('time_spent', models.PositiveIntegerField(blank=True, help_text='Time spent in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Form Analytics Event',
                'verbose_name_plural': 'Form Analytics Events',
                'db_table': 'contact_form_analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='contact_for_session_93d533_idx'), models.Index(fields=['event_type'], name='contact_for_event_t_23dadb_idx'), models.Index(fields=['created_at'], name='contact_for_created_04b780_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(help_text='Unique reference number for this submission', max_length=50, unique=True)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('template', 'Template'), ('service', 'Service'), ('pricing', 'Pricing'), ('referral', 'Referral'), ('social', 'Social Media'), ('search', 'Search Engine'), ('other', 'Other')], default='direct', help_text='How the user found us', max_length=50)),
                ('referrer', models.URLField(blank=True, help_text='Referring URL', null=True)),
                ('template_id', models.CharField(blank=True, help_text='Template that led to this inquiry', max_length=100, null=True)),
                ('service_id', models.CharField(blank=True, help_text='Service that led to this inquiry', max_length=100, null=True)),
                ('primary_goal', models.CharField(choices=[('new_website', 'Build a New Website'), ('redesign', 'Redesign Existing Site'), ('add_features', 'Add Features'), ('consultation', 'Consultation'), ('other', 'Something Else')], help_text='Primary goal for the project', max_length=50)),
                ('business_name', models.CharField(help_text='Business or company name', max_length=255)),
                ('industry', models.CharField(help_text='Business industry', max_length=100)),
                ('current_website', models.URLField(blank=True, help_text='Current website URL if any', null=True)),
                ('website_type', models.CharField(choices=[('ecommerce', 'E-commerce'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('corporate', 'Corporate'), ('landing', 'Landing Page'), ('custom', 'Custom')], help_text='Type of website needed', max_length=50)),
                ('services_needed', models.JSONField(default=list, help_text='List of services needed')),
                ('budget_range', models.CharField(choices=[('pay_as_you_go', 'Pay-As-You-Go (£59/mo)'), ('fully_managed', 'Fully Managed (£249/mo)'), ('full_ownership', 'Full Ownership (Custom)'), ('custom', 'Custom Budget')], help_text='Budget range for the project', max_length=50)),
                ('timeline', models.CharField(choices=[('flexible', 'Flexible'), ('urgent', 'Urgent (ASAP)'), ('specific', 'Specific Date')], help_text='Project timeline preference', max_length=50)),
                ('target_date', models.DateField(blank=True, help_text='Specific target date if timeline is specific', null=True)),
                ('additional_requirements', models.TextField(blank=True, help_text='Additional project requirements', null=True)),
                ('contact_name', models.CharField(help_text='Contact person name', max_length=255)),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('either', 'Either')], default='email', help_text='Preferred contact method', max_length=20)),
                ('best_time_to_reach', models.CharField(choices=[('morning', 'Morning (9AM-12PM)'), ('afternoon', 'Afternoon (12PM-5PM)'), ('evening', 'Evening (5PM-8PM)'), ('anytime', 'Anytime')], default='anytime', help_text='Best time to reach the contact', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='new', help_text='Current status of the submission', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('form_data', models.JSONField(default=dict, help_text='Complete form data as submitted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_response_at', models.DateTimeField(blank=True, help_text='When the first response was sent', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the submission was completed', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether confirmation email was sent')),
                ('admin_notified', models.BooleanField(default=False, help_text='Whether admin was notified')),
                ('follow_up_count', models.PositiveIntegerField(default=0, help_text='Number of follow-up communications')),
                ('last_contact_at', models.DateTimeField(blank=True, help_text='Last time we contacted the client', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contact_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(help_text='URL to the uploaded file')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contact.contactsubmission')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission Attachment',
                'verbose_name_plural': 'Submission Attachments',
                'db_table': 'submission_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('internal', 'Internal Note'), ('client_communication', 'Client Communication'), ('status_change', 'Status Change'), ('follow_up', 'Follow-up'), ('meeting', 'Meeting Notes')], default='internal', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='Private notes are not visible to clients')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_notes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contact.contactsubmission')),
            ],
            options={
                'verbose_name': 'Submission Note',
                'verbose_name_plural': 'Submission Notes',
                'db_table': 'submission_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['status'], name='contact_sub_status_88fb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['created_at'], name='contact_sub_created_54b02f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['email'], name='contact_sub_email_903821_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['reference_number'], name='contact_sub_referen_7c78c7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['assigned_to'], name='contact_sub_assigne_678da4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['priority'], name='contact_sub_priorit_9bee81_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['source'], name='contact_sub_source_8e1998_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionnote',
            index=models.Index(fields=['submission', 'created_at'], name='submission__submiss_6afc3c_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionnote',
            index=models.Index(fields=['author'], name='submission__author__d3732d_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionnote',
            index=models.Index(fields=['note_type'], name='submission__note_ty_493fa2_idx'),
        ),
    ]
