# Generated by Django 6.0.1 on 2026-02-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth0_sub',
            field=models.CharField(blank=True, help_text='Auth0 subject identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('custom', 'Custom'), ('auth0', 'Auth0')], default='custom', help_text='Authentication provider', max_length=20),
        ),
    ]
