# Generated by Django 6.0.1 on 2026-01-30 23:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('slug', models.SlugField(help_text='URL slug', max_length=255, unique=True)),
                ('industry', models.CharField(choices=[('barbershops', 'Barbershops'), ('cafes', 'Cafes & Eateries'), ('home_services', 'Home Services'), ('retail', 'Retail & E-commerce'), ('professional_services', 'Professional Services'), ('healthcare', 'Healthcare'), ('fitness', 'Fitness & Wellness'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('automotive', 'Automotive'), ('general', 'General Business')], help_text='Target industry', max_length=50)),
                ('description', models.TextField(help_text='Template description')),
                ('preview_image', models.URLField(help_text='Preview image URL')),
                ('demo_url', models.URLField(blank=True, help_text='Live demo URL', null=True)),
                ('features', models.JSONField(default=list, help_text='List of template features')),
                ('badge', models.CharField(blank=True, help_text='Badge text (e.g., Popular, New, High Conversion)', max_length=50, null=True)),
                ('price', models.CharField(blank=True, help_text='Price display text', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['industry'], name='templates_industr_96de46_idx'), models.Index(fields=['is_active'], name='templates_is_acti_1697a7_idx'), models.Index(fields=['is_featured'], name='templates_is_feat_63f750_idx'), models.Index(fields=['display_order'], name='templates_display_0787c5_idx')],
            },
        ),
    ]
